package service

import (
	"bytes"
	"net/netip"
	"strings"
	"text/template"

	"github.com/mhsanaei/3x-ui/v3/database/model"
)

// ServerConfigTemplate holds data for AmneziaWG server configuration template
type ServerConfigTemplate struct {
	InterfaceName string
	PrivateKey    string
	Address       string
	ListenPort    int
	DNS           string
	MTU           int
	SourceCIDR    string

	// AmneziaWG 2.0 obfuscation parameters
	Jc   int
	Jmin int
	Jmax int
	S1   int
	S2   int
	S3   int
	S4   int
	H1   string
	H2   string
	H3   string
	H4   string
	I1   string
	I2   string
	I3   string
	I4   string
	I5   string

	// Peers
	Peers []PeerConfigTemplate
}

// PeerConfigTemplate holds data for peer configuration template
type PeerConfigTemplate struct {
	Name string

	PrivateKey          string
	PublicKey           string
	PresharedKey        string
	Address             string
	AllowedIPs          string
	Endpoint            string
	PersistentKeepalive int
	DNS                 string
	MTU                 int

	// Server public key for client config
	ServerPublicKey string

	// AmneziaWG 2.0 obfuscation parameters (same as server for client)
	Jc   int
	Jmin int
	Jmax int
	S1   int
	S2   int
	S3   int
	S4   int
	H1   string
	H2   string
	H3   string
	H4   string
	I1   string
	I2   string
	I3   string
	I4   string
	I5   string
}

// Server config template - AmneziaWG 2.0 format
const serverConfigTmpl = `# AmneziaWG Server Configuration
# Generated by 3X-UI Amnezia
# Interface: {{.InterfaceName}}

[Interface]
PrivateKey = {{.PrivateKey}}
Address = {{.Address}}
ListenPort = {{.ListenPort}}
{{- if .MTU}}
MTU = {{.MTU}}
{{- end}}
SaveConfig = false
PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -C FORWARD -i {{.InterfaceName}} -j ACCEPT 2>/dev/null || iptables -A FORWARD -i {{.InterfaceName}} -j ACCEPT; iptables -C FORWARD -o {{.InterfaceName}} -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || iptables -A FORWARD -o {{.InterfaceName}} -m state --state ESTABLISHED,RELATED -j ACCEPT; iptables -t nat -C POSTROUTING -s {{.SourceCIDR}} -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s {{.SourceCIDR}} -j MASQUERADE
PostDown = iptables -D FORWARD -i {{.InterfaceName}} -j ACCEPT 2>/dev/null || true; iptables -D FORWARD -o {{.InterfaceName}} -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true; iptables -t nat -D POSTROUTING -s {{.SourceCIDR}} -j MASQUERADE 2>/dev/null || true

# AmneziaWG 2.0 Obfuscation Parameters
Jc = {{.Jc}}
Jmin = {{.Jmin}}
Jmax = {{.Jmax}}
S1 = {{.S1}}
S2 = {{.S2}}
S3 = {{.S3}}
S4 = {{.S4}}
H1 = {{.H1}}
H2 = {{.H2}}
H3 = {{.H3}}
H4 = {{.H4}}
{{- if .I1}}
I1 = {{.I1}}
{{- end}}
{{- if .I2}}
I2 = {{.I2}}
{{- end}}
{{- if .I3}}
I3 = {{.I3}}
{{- end}}
{{- if .I4}}
I4 = {{.I4}}
{{- end}}
{{- if .I5}}
I5 = {{.I5}}
{{- end}}

{{- range $peer := .Peers}}

[Peer]
# {{$peer.Name}}
PublicKey = {{$peer.PublicKey}}
{{- if $peer.PresharedKey}}
PresharedKey = {{$peer.PresharedKey}}
{{- end}}
AllowedIPs = {{$peer.AllowedIPs}}
{{- end}}
`

// Client config template - AmneziaWG 2.0 format
const clientConfigTmpl = `[Interface]
PrivateKey = {{.PrivateKey}}
{{- if .Address}}
Address = {{.Address}}
{{- end}}
{{- if .DNS}}
DNS = {{.DNS}}
{{- end}}
{{- if .MTU}}
MTU = {{.MTU}}
{{- end}}

# AmneziaWG 2.0 Obfuscation Parameters
Jc = {{.Jc}}
Jmin = {{.Jmin}}
Jmax = {{.Jmax}}
S1 = {{.S1}}
S2 = {{.S2}}
S3 = {{.S3}}
S4 = {{.S4}}
H1 = {{.H1}}
H2 = {{.H2}}
H3 = {{.H3}}
H4 = {{.H4}}
{{- if .I1}}
I1 = {{.I1}}
{{- end}}
{{- if .I2}}
I2 = {{.I2}}
{{- end}}
{{- if .I3}}
I3 = {{.I3}}
{{- end}}
{{- if .I4}}
I4 = {{.I4}}
{{- end}}
{{- if .I5}}
I5 = {{.I5}}
{{- end}}

[Peer]
PublicKey = {{.ServerPublicKey}}
{{- if .PresharedKey}}
PresharedKey = {{.PresharedKey}}
{{- end}}
{{- if .Endpoint}}
Endpoint = {{.Endpoint}}
{{- end}}
{{- if .AllowedIPs}}
AllowedIPs = {{.AllowedIPs}}
{{- end}}
{{- if .PersistentKeepalive}}
PersistentKeepalive = {{.PersistentKeepalive}}
{{- end}}
`

// RenderServerConfig renders the AmneziaWG server configuration using template
func RenderServerConfig(server *model.AmneziaServer, peers []model.AmneziaPeer, obf *model.AmneziaObfuscation) (string, error) {
	tmpl, err := template.New("server").Parse(serverConfigTmpl)
	if err != nil {
		return "", err
	}

	// Build peer templates
	peerTemplates := make([]PeerConfigTemplate, 0, len(peers))
	for _, peer := range peers {
		allowedIPs := strings.TrimSpace(peer.Address)
		if allowedIPs == "" {
			continue
		}
		if idx := len(allowedIPs) - 1; idx > 0 && allowedIPs[idx:] == "/32" {
			// Already has CIDR
		} else if !containsCIDR(allowedIPs) {
			allowedIPs = allowedIPs + "/32"
		}
		peerTemplates = append(peerTemplates, PeerConfigTemplate{
			Name:         peer.Name,
			PublicKey:    peer.PublicKey,
			PresharedKey: peer.PresharedKey,
			AllowedIPs:   allowedIPs,
		})
	}

	data := struct {
		InterfaceName string
		PrivateKey    string
		Address       string
		ListenPort    int
		DNS           string
		MTU           int
		SourceCIDR    string
		Jc            int
		Jmin          int
		Jmax          int
		S1            int
		S2            int
		S3            int
		S4            int
		H1            string
		H2            string
		H3            string
		H4            string
		I1            string
		I2            string
		I3            string
		I4            string
		I5            string
		Peers         []PeerConfigTemplate
	}{
		InterfaceName: server.InterfaceName,
		PrivateKey:    server.PrivateKey,
		Address:       server.Address,
		ListenPort:    server.ListenPort,
		DNS:           server.DNS,
		MTU:           server.MTU,
		SourceCIDR:    sourceCIDR(server.Address),
		Jc:            obf.Jc,
		Jmin:          obf.Jmin,
		Jmax:          obf.Jmax,
		S1:            obf.S1,
		S2:            obf.S2,
		S3:            obf.S3,
		S4:            obf.S4,
		H1:            obf.H1,
		H2:            obf.H2,
		H3:            obf.H3,
		H4:            obf.H4,
		I1:            obf.I1,
		I2:            obf.I2,
		I3:            obf.I3,
		I4:            obf.I4,
		I5:            obf.I5,
		Peers:         peerTemplates,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// RenderClientConfig renders the AmneziaWG client configuration using template
func RenderClientConfig(peer *model.AmneziaPeer, server *model.AmneziaServer, obf *model.AmneziaObfuscation) (string, error) {
	tmpl, err := template.New("client").Parse(clientConfigTmpl)
	if err != nil {
		return "", err
	}

	data := PeerConfigTemplate{
		PrivateKey:          peer.PrivateKey,
		PublicKey:           peer.PublicKey,
		PresharedKey:        peer.PresharedKey,
		Address:             peer.Address,
		AllowedIPs:          peer.AllowedIPs,
		Endpoint:            peer.Endpoint,
		PersistentKeepalive: peer.PersistentKeepalive,
		DNS:                 server.DNS,
		MTU:                 server.MTU,
		ServerPublicKey:     server.PublicKey,
		Jc:                  obf.Jc,
		Jmin:                obf.Jmin,
		Jmax:                obf.Jmax,
		S1:                  obf.S1,
		S2:                  obf.S2,
		S3:                  obf.S3,
		S4:                  obf.S4,
		H1:                  obf.H1,
		H2:                  obf.H2,
		H3:                  obf.H3,
		H4:                  obf.H4,
		I1:                  obf.I1,
		I2:                  obf.I2,
		I3:                  obf.I3,
		I4:                  obf.I4,
		I5:                  obf.I5,
	}

	// Use server endpoint if peer doesn't have one
	if data.Endpoint == "" {
		data.Endpoint = server.Endpoint
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// containsCIDR checks if the address string contains a CIDR notation
func containsCIDR(addr string) bool {
	for i := 0; i < len(addr); i++ {
		if addr[i] == '/' {
			return true
		}
	}
	return false
}

func sourceCIDR(address string) string {
	addr := strings.TrimSpace(address)
	if addr == "" {
		return "10.0.0.0/24"
	}
	prefix, err := netip.ParsePrefix(addr)
	if err == nil {
		return prefix.Masked().String()
	}
	return addr
}

func (s *AmneziaService) generateServerConfig(server *model.AmneziaServer, peers []model.AmneziaPeer) string {
	obf := s.parseObfuscationStruct(server.ObfuscationJSON)
	config, err := RenderServerConfig(server, peers, obf)
	if err != nil {
		return ""
	}
	if strings.TrimSpace(server.ObfuscationJSON) == "" {
		config = stripObfuscationParams(config)
	}
	return config
}

func stripObfuscationParams(config string) string {
	lines := strings.Split(config, "\n")
	filtered := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "# AmneziaWG 2.0 Obfuscation Parameters" ||
			strings.HasPrefix(trimmed, "Jc =") ||
			strings.HasPrefix(trimmed, "Jmin =") ||
			strings.HasPrefix(trimmed, "Jmax =") ||
			strings.HasPrefix(trimmed, "S1 =") ||
			strings.HasPrefix(trimmed, "S2 =") ||
			strings.HasPrefix(trimmed, "S3 =") ||
			strings.HasPrefix(trimmed, "S4 =") ||
			strings.HasPrefix(trimmed, "H1 =") ||
			strings.HasPrefix(trimmed, "H2 =") ||
			strings.HasPrefix(trimmed, "H3 =") ||
			strings.HasPrefix(trimmed, "H4 =") ||
			strings.HasPrefix(trimmed, "I1 =") ||
			strings.HasPrefix(trimmed, "I2 =") ||
			strings.HasPrefix(trimmed, "I3 =") ||
			strings.HasPrefix(trimmed, "I4 =") ||
			strings.HasPrefix(trimmed, "I5 =") {
			continue
		}
		filtered = append(filtered, line)
	}
	return strings.Join(filtered, "\n")
}
