package service

import (
	"bytes"
	"text/template"

	"github.com/mhsanaei/3x-ui/v3/database/model"
)

// ServerConfigTemplate holds data for AmneziaWG server configuration template
type ServerConfigTemplate struct {
	PrivateKey string
	Address    string
	ListenPort int
	DNS        string
	MTU        int

	// AmneziaWG 2.0 obfuscation parameters
	Jc   int
	Jmin int
	Jmax int
	S1   int
	S2   int
	S3   int
	S4   int
	H1   string
	H2   string
	H3   string
	H4   string
	I1   string
	I2   string
	I3   string
	I4   string
	I5   string

	// Peers
	Peers []PeerConfigTemplate
}

// PeerConfigTemplate holds data for peer configuration template
type PeerConfigTemplate struct {
	Name string

	PrivateKey       string
	PublicKey        string
	PresharedKey     string
	Address          string
	AllowedIPs       string
	Endpoint         string
	PersistentKeepalive int
	DNS              string
	MTU              int

	// Server public key for client config
	ServerPublicKey string

	// AmneziaWG 2.0 obfuscation parameters (same as server for client)
	Jc   int
	Jmin int
	Jmax int
	S1   int
	S2   int
	S3   int
	S4   int
	H1   string
	H2   string
	H3   string
	H4   string
	I1   string
	I2   string
	I3   string
	I4   string
	I5   string
}

// Server config template - AmneziaWG 2.0 format
const serverConfigTmpl = `# AmneziaWG Server Configuration
# Generated by 3X-UI Amnezia
# Interface: {{.InterfaceName}}

[Interface]
PrivateKey = {{.PrivateKey}}
Address = {{.Address}}
ListenPort = {{.ListenPort}}
{{- if .DNS}}
DNS = {{.DNS}}
{{- end}}
{{- if .MTU}}
MTU = {{.MTU}}
{{- end}}

# AmneziaWG 2.0 Obfuscation Parameters
Jc = {{.Jc}}
Jmin = {{.Jmin}}
Jmax = {{.Jmax}}
S1 = {{.S1}}
S2 = {{.S2}}
S3 = {{.S3}}
S4 = {{.S4}}
H1 = {{.H1}}
H2 = {{.H2}}
H3 = {{.H3}}
H4 = {{.H4}}
{{- if .I1}}
I1 = {{.I1}}
{{- end}}
{{- if .I2}}
I2 = {{.I2}}
{{- end}}
{{- if .I3}}
I3 = {{.I3}}
{{- end}}
{{- if .I4}}
I4 = {{.I4}}
{{- end}}
{{- if .I5}}
I5 = {{.I5}}
{{- end}}

{{- range $peer := .Peers}}

[Peer]
# {{$peer.Name}}
PublicKey = {{$peer.PublicKey}}
{{- if $peer.PresharedKey}}
PresharedKey = {{$peer.PresharedKey}}
{{- end}}
AllowedIPs = {{$peer.AllowedIPs}}
{{- end}}
`

// Client config template - AmneziaWG 2.0 format
const clientConfigTmpl = `[Interface]
PrivateKey = {{.PrivateKey}}
{{- if .Address}}
Address = {{.Address}}
{{- end}}
{{- if .DNS}}
DNS = {{.DNS}}
{{- end}}
{{- if .MTU}}
MTU = {{.MTU}}
{{- end}}

# AmneziaWG 2.0 Obfuscation Parameters
Jc = {{.Jc}}
Jmin = {{.Jmin}}
Jmax = {{.Jmax}}
S1 = {{.S1}}
S2 = {{.S2}}
S3 = {{.S3}}
S4 = {{.S4}}
H1 = {{.H1}}
H2 = {{.H2}}
H3 = {{.H3}}
H4 = {{.H4}}
{{- if .I1}}
I1 = {{.I1}}
{{- end}}
{{- if .I2}}
I2 = {{.I2}}
{{- end}}
{{- if .I3}}
I3 = {{.I3}}
{{- end}}
{{- if .I4}}
I4 = {{.I4}}
{{- end}}
{{- if .I5}}
I5 = {{.I5}}
{{- end}}

[Peer]
PublicKey = {{.ServerPublicKey}}
{{- if .PresharedKey}}
PresharedKey = {{.PresharedKey}}
{{- end}}
{{- if .Endpoint}}
Endpoint = {{.Endpoint}}
{{- end}}
{{- if .AllowedIPs}}
AllowedIPs = {{.AllowedIPs}}
{{- end}}
{{- if .PersistentKeepalive}}
PersistentKeepalive = {{.PersistentKeepalive}}
{{- end}}
`

// RenderServerConfig renders the AmneziaWG server configuration using template
func RenderServerConfig(server *model.AmneziaServer, peers []model.AmneziaPeer, obf *model.AmneziaObfuscation) (string, error) {
	tmpl, err := template.New("server").Parse(serverConfigTmpl)
	if err != nil {
		return "", err
	}

	// Build peer templates
	peerTemplates := make([]PeerConfigTemplate, 0, len(peers))
	for _, peer := range peers {
		allowedIPs := peer.Address
		if idx := len(allowedIPs) - 1; idx > 0 && allowedIPs[idx:] == "/32" {
			// Already has CIDR
		} else if !containsCIDR(allowedIPs) {
			allowedIPs = allowedIPs + "/32"
		}
		peerTemplates = append(peerTemplates, PeerConfigTemplate{
			Name:          peer.Name,
			PublicKey:     peer.PublicKey,
			PresharedKey:  peer.PresharedKey,
			AllowedIPs:    allowedIPs,
		})
	}

	data := struct {
		InterfaceName string
		PrivateKey    string
		Address       string
		ListenPort    int
		DNS           string
		MTU           int
		Jc            int
		Jmin          int
		Jmax          int
		S1            int
		S2            int
		S3            int
		S4            int
		H1            string
		H2            string
		H3            string
		H4            string
		I1            string
		I2            string
		I3            string
		I4            string
		I5            string
		Peers         []PeerConfigTemplate
	}{
		InterfaceName: server.InterfaceName,
		PrivateKey:    server.PrivateKey,
		Address:       server.Address,
		ListenPort:    server.ListenPort,
		DNS:           server.DNS,
		MTU:           server.MTU,
		Jc:            obf.Jc,
		Jmin:          obf.Jmin,
		Jmax:          obf.Jmax,
		S1:            obf.S1,
		S2:            obf.S2,
		S3:            obf.S3,
		S4:            obf.S4,
		H1:            obf.H1,
		H2:            obf.H2,
		H3:            obf.H3,
		H4:            obf.H4,
		I1:            obf.I1,
		I2:            obf.I2,
		I3:            obf.I3,
		I4:            obf.I4,
		I5:            obf.I5,
		Peers:         peerTemplates,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// RenderClientConfig renders the AmneziaWG client configuration using template
func RenderClientConfig(peer *model.AmneziaPeer, server *model.AmneziaServer, obf *model.AmneziaObfuscation) (string, error) {
	tmpl, err := template.New("client").Parse(clientConfigTmpl)
	if err != nil {
		return "", err
	}

	data := PeerConfigTemplate{
		PrivateKey:         peer.PrivateKey,
		PublicKey:          peer.PublicKey,
		PresharedKey:       peer.PresharedKey,
		Address:            peer.Address,
		AllowedIPs:         peer.AllowedIPs,
		Endpoint:           peer.Endpoint,
		PersistentKeepalive: peer.PersistentKeepalive,
		DNS:                server.DNS,
		MTU:                server.MTU,
		ServerPublicKey:    server.PublicKey,
		Jc:                 obf.Jc,
		Jmin:               obf.Jmin,
		Jmax:               obf.Jmax,
		S1:                 obf.S1,
		S2:                 obf.S2,
		S3:                 obf.S3,
		S4:                 obf.S4,
		H1:                 obf.H1,
		H2:                 obf.H2,
		H3:                 obf.H3,
		H4:                 obf.H4,
		I1:                 obf.I1,
		I2:                 obf.I2,
		I3:                 obf.I3,
		I4:                 obf.I4,
		I5:                 obf.I5,
	}

	// Use server endpoint if peer doesn't have one
	if data.Endpoint == "" {
		data.Endpoint = server.Endpoint
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// containsCIDR checks if the address string contains a CIDR notation
func containsCIDR(addr string) bool {
	for i := 0; i < len(addr); i++ {
		if addr[i] == '/' {
			return true
		}
	}
	return false
}