services:
  amneziawg:
    image: vnxme/amneziawg-go:latest
    container_name: 3xui_amneziawg
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/amnezia/amneziawg/:/etc/amnezia/amneziawg/
      - ./docker/amneziawg/entrypoint.sh:/entrypoint.sh:ro
    environment:
      LOG_LEVEL: "info"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "amneziawg-go"
    entrypoint:
      - /bin/sh
      - /entrypoint.sh
    restart: unless-stopped
